### ISSUE TITLE
video is getting freeze not able to share ar content 

### ISSUE THREAD

**Issue by behappiest** [digitallysavvy/AR-Remote-Support#7]
Hi I was trying to use this github repo master branch,
I am able to lauch the app and join the room
I can see my video in both the phones
but I am not able to draw anything and rear camera video feed is not visible in another phone.
Please let me know what need to be improved from my side.

Thanks

**Comment by digitallysavvy** [comment]
@behappiest What devices are you using to test?

**Comment by behappiest** [comment]
@digitallysavvy  i tried in iPhone XR and iphone 6s.

**Comment by digitallysavvy** [comment]
Which device is using the AR session? From my experience its best to use the XR to "create" the channel and have the "6s" join the channel.

**Comment by behappiest** [comment]
I tried both, i tried to create session from XR but from XR video is freezing within 1 sec, and same freeze image is visible in 6s but when I create session from 6s, in 6s only blank screen comes and nothing is visible in XR

**Comment by digitallysavvy** [comment]
Are there any errors displayed in the Xcode logger?

**Comment by digitallysavvy** [comment]
@behappiest can you please share logs for the issue you are experiencing?

**Comment by digitallysavvy** [comment]
@behappiest are you still experiencing this issue? were you able to resolve it?

**Comment by behappiest** [comment]
Hi @digitallysavvy  i will share the logs after 15 Jan, i am out for some work.

**Comment by digitallysavvy** [comment]
@behappiest I think I may have found your issue. When running this app within iOS13 on iPhone X (or above)  there is an error thrown by the AVSession, for some reason it fails to initialize. This issue does not occur on iPadOS 13 nor does it occur on iPhone 7. It is caused when you attempt to use the audio data from ARKit. 

I have filed a bug with Agora.io's engineers. In the mean team, you can fix this issue by disabling the audio provided by ARKit comment out [ARBroadcaster line 62](https://github.com/digitallysavvy/AR-Remote-Support/blob/8a77bb8567ec68659a8dbb81e731d95e2d9105d1/AR%20Remote%20Support/ARSupportBroadcasterViewController.swift#L62) and don't use a custom Audio Source...comment out [ARBroadcaster line 53](https://github.com/digitallysavvy/AR-Remote-Support/blob/8a77bb8567ec68659a8dbb81e731d95e2d9105d1/AR%20Remote%20Support/ARSupportBroadcasterViewController.swift#L53)

Let me know if this resolves your issue.

**Comment by behappiest** [comment]
Hi @digitallysavvy  I tried your solution and its working, Thanks for your support.
