### ISSUE TITLE
No such module 'AgoraRtcEngineKit'

### ISSUE THREAD

**Issue by Vishnupriya5htc** [digitallysavvy/AR-Remote-Support#8]
while running this sample, I am getting No such module 'AgoraRtcEngineKit' issue

**Comment by digitallysavvy** [comment]
Did you run `pod install` ?

**Comment by Vishnupriya5htc** [comment]
Yes

**Comment by Vishnupriya5htc** [comment]
i have faced the issue No such module 'AgoraRtcEngineKit'. Also I have tried in Swift 4.2 and 5 versions also. But I am getting same error.

**Comment by digitallysavvy** [comment]
It seems that the pod did not install correctly or for some reason Xcode isn't recognizing it. Can you try closing Xcode, re-run `pod install` and then open the  `.xcworkspace` file.

Let me know if this corrects your issue.

> as a side note: I recommend that you use Swift 4.2 for running this project. If must use Swift 5, please update the ARVideoKit dependency in the `pod file`

**Comment by digitallysavvy** [comment]
@Vishnupriya5htc any updates? Were you able to get the project working?

**Comment by digitallysavvy** [comment]
@Vishnupriya5htc I assume you have resolved this issue.
